### ISSUE TITLE
访问报错了

### ISSUE THREAD

**Issue by zhulichao** [ant-design/scaffold-market#116]
浏览器：360浏览器 版本号：8.1.1.258 内核版本：45.0.2454.101
![err](https://user-images.githubusercontent.com/18158633/29311185-655d7c4a-81e3-11e7-83ce-e7a246f912ca.png)

**Comment by afc163** [comment]
登录一下试试。

**Comment by zhulichao** [comment]
现在好了，没登录也没报错。
