### ISSUE TITLE
被收录的项目。多久会显示到主页上

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/scaffold-market#195]
被收录的项目。多久会显示到主页上

**Comment by afc163** [comment]
我晚些时候排查一下

**Comment by weiq** [comment]
我的也没有显示

**Comment by mowatermelon** [comment]
![image](https://user-images.githubusercontent.com/18508817/39975560-e3605e7e-5761-11e8-8ac1-2248f0606b02.png)


我提交的也是被merge了，但是也没有显示
